aleph-im/aleph-docs

docs/nodes/compute.md
Added the links to the installation and registration guide for the CRNs.
=> [UPDATE] Update compute.md

docs/computing/custom domain/Adding a Custom Domain.md
Added this instruction page to help the users set up their DNS records for their programs or instances.
=> [Create] Adding a Custom Domain.md

docs/protocol/chains.md
This branch adds documentation on the support of the different chains in aleph.im .
=> Document chain support

docs/tools/IPFS-Pinning.md
Added this to the Tools section of the docs.
The new IPFS Pinning flow will be able to link to this to better understand our decentralized pinning offering.
=> [CREATE] IPFS-Pinning.md

.github/workflows/actions.yaml
The goal of this branch is to publish the documentation automatically on merge.
This is work in progress.
=> Deploy docs automatically on a domain name

docs/libraries/Aleph.im-TypeScript-SDK/accounts.md, docs/libraries/Aleph.im-TypeScript-SDK/aggregates.md, docs/libraries/Aleph.im-TypeScript-SDK/index.md, docs/libraries/Aleph.im-TypeScript-SDK/instances.md, docs/libraries/Aleph.im-TypeScript-SDK/posts.md, docs/libraries/typescript.md
Very similar to the existing Python SDK docs.
=> Add better docs of the TS SDK v1.0.0-alpha1 (after the refactoring).

docs/libraries/python-sdk/accounts.md
Adding some exemple for every language about the creation of an account using tabs:
=> Refactor the account management for the Python SDK

mkdocs.yml
The way the navigation was organized was not the best way for the user to understand and use the project as a whole.
Solution: Reorganize the navigation a little, placing some sections first and more complex ones at the end.
=> Fixed: Poor user experience during navigation

docs/libraries/typescript-sdk/troubleshooting.md, mkdocs.yml
- With a request to report issues to the GH repo.
- Addresses installs not working under Vite
=> Add TS SDK Troubleshooting Guide

docs/protocol/object-types/storage.md
Small typo causing formatting errors 😄
=> Fix small typo in STORE message docs

.github/workflows/actions.yaml, docs/tools/webconsole/write_your_code.md, mkdocs.yml, pyproject.toml
Usage.md and Documentation.md were the same page, so we keeped usage.md but it was not deleted from the navigation insided the mkdocs file.
Solution: Removing the navigation related to Documentation.md
=> FIX: Broken page in the navigation

docs/protocol/chains.md
https://docs.aleph.im/protocol/chains/
=> [*] add wallet connect to chain list

mkdocs.yml
See https://www.theregister.com/2024/06/25/polyfillio_china_crisis/
=> fix: due to security issues, avoid using polyfill.io

.github/workflows/actions.yaml, mkdocs.yml, pyproject.toml
The privacy plugin offers a streamlined solution for automatically self-hosting external assets.
https://squidfunk.github.io/mkdocs-material/plugins/privacy/
9.5.0 December 7, 2023 - Added privacy plugin: automatic downloading of external assets
=> Fix: Use plugin privacy for self-hosting external assets

docs/nodes/core/backups.md
Hey guys !
I think there's some confusion here about the doc between CRN and CCN.
Btw, good job for your doc
=> feat(doc): change CRN by CCN

docs/nodes/reliability/metrics.md, test/python_test.py
This updates the documentation on metrics and adds examples on how to fetch metrics.
New code example is tested using `pytest`.
=> Metrics update with examples

docs/computing/confidential/instance.md
The paramters for the aleph-client changed and it was not up to date
Jira: ALEPH-198
=> Update CoCo documentation

docs/tools/aleph-client/usage.md
=> Update aleph-client usage documentation

docs/computing/confidential/troubleshooting.md
- Bad Measurement
- Impossible to SSH
- Wrong decryption password
=> Add toubleshooting information for confidential VM

docs/tools/web3-hosting.md
https://beta.docs.aleph.im/tools/web3-hosting/
=> Add pricing and AI sections to web3-hosting

docs/tools/aleph-client/usage.md
Following:
- https://github.com/aleph-im/aleph-client/pull/312
- https://github.com/aleph-im/aleph-client/pull/311
Changes:
- Update with latest CLI changes
- Fix wrong args indentation for volumes
- Auto-replace username and private-key-file with generic ones
=> Update CLI generated docs

docs/tools/aleph-client/usage.md
Update of CLI docs after recent changes:
- Rework on aggregate cmds (fixes, improvements, and permissions)
- Improvements on node cmds
- Minor fixes on program cmds
=> Update CLI docs: aggregate, node, program cmds

docs/computing/confidential/instance.md
Demo: [new](https://ipfs-2.aleph.im/ipfs/QmTqUfnZqQEwuvoBoav2bbQwFtBeiUfpoW5YsLgfhMgBc2/computing/confidential/instance/)
To compare with current version: [old](https://docs.aleph.im/computing/confidential/instance/)
=> Improve coco instance creation docs

docs/tools/aleph-client/usage.md
[Demo](https://ipfs-2.aleph.im/ipfs/QmYabU7ZsiRi7YS31DnKCtaJzqdrnoR9PmFfTyDz7u1Weg/tools/aleph-client/usage/)
=> Update CLI docs [pricing system / GPU]

docs/nodes/compute/installation/debian-12.md, docs/nodes/compute/installation/ubuntu-22.04.md, docs/nodes/compute/installation/ubuntu-24.04.md
Theses commands are easier to read and thus a bit less scary for an user to enter blindly as root on is server
=> Make command to download last aleph-vm a bit less scary

docs/tools/aleph-client/usage.md
Update after latest CLI fixes: [Demo](https://ipfs-2.aleph.im/ipfs/QmP59QUGWqQ3bztFN2pDzzpNdjNHKYMgcFpWWPE3CQX3iF/tools/aleph-client/usage/)
=> Update CLI docs post fixes
